### ISSUE TITLE
Links appearing incorrect on Startpage

### ISSUE THREAD

**Issue by Rickos99** [Rickos99/To-Do-list-with-login#4]
On smaller screens these two links, _below_, to sign in/ sign up is moving around in the `<p>` tag.
#### HTML
```HTML
<div class="landing-image-shell">
   <div class="landing-image-group">
      <h1>TO-DO list</h1>
      <p><a href="log.php">Logga in</a><a href="reg.php">Registrera</a></p>
   </div>
</div>
```

#### CSS
```CSS
.landing-image-group {
	text-align: center;
	top: 40%;
	left: 50%;
	transform: translate(-50%);
	position: fixed;
	width: 100%;
}

.landing-image-group h1 {
	color: #FFF;
	font-size: 300%;
}

.landing-image-group p {
	padding-bottom: 50px;
}

.landing-image-group p a {
	color: #FFF;
	margin: 20px;
	border: 2px solid #fff;
	border-radius: 20px;
	padding: 10px;
	transition: 150ms ease-in-out;
}
```
